### ISSUE TITLE
Using nan 

### ISSUE THREAD

**Issue by mike820324** [dotSlashLu/nodescws#9]
Hello, 
I just fork this project and change the code a bit.
The following is the diff
https://github.com/mike820324/nodescws/commit/85eb2e5980501c0abaac4ffaa6ebe55ce594b0e5

I have use nan so that this module can work in more node versions.
With the above modification, now nodescws can work on iojs too.
:)
Should I send a pull request ??

**Comment by mike820324** [comment]
b.t.w, the code indent is messed up, sorry about that,
I have change the indent back in the newest commit.
Thanks.

**Comment by dotSlashLu** [comment]
@mike820324 Hi, sorry for my late reply, message box overflow... A pull request is appreciated, thanks for your advice and work, I'll test and publish it.

**Comment by mike820324** [comment]
@dotSlashLu I have sent the PR, tks. 
:+1:

**Comment by dotSlashLu** [comment]
@mike820324 PR accepted and new version has been released to npm. To thanks for your work I listed you in [readme](https://github.com/dotSlashLu/nodescws#contributors) ;)
